# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "My eval"

prompts:
  - "Were there any presentation about {{topic}}?"

providers:
  - id: file:///Praca\meetjs\rags\dist\custom-api-provider.cjs

tests:
  - vars:
      topic: monitoring

  - vars:
      topic: microservices
    assert:
      - type: icontains
        value: microservices

      - type: llm-rubric
        value: there were presentations about microservices

  - vars:
      topic: new york city
    assert:
      - type: llm-rubric
        value: there were no presentations about new york city
